Reduce flakeness for emulator integration tests
This CL tries rebooting the emulator process if it cannot finish booting
within a reasonable amount of time.

It looks like the rvc emulator has 0.1% of boot failure rate.

Other changes include:
1. Redirect all stderr, which seems to block java exec a lot.
2. Run "adb reconnect" after killing the emulator. Otherwise there is a
low chance (<0.1%) that adb is not updated.

Bug: 149954568
Test: --runs_per_test=10000 --config=remote tools/base/bazel/avd/sample:emulator_test

Change-Id: I838e2e62f5bca929cf237d1a086994ca6d4051a1

diff --git a/bazel/avd/emulator_launcher.sh.template b/bazel/avd/emulator_launcher.sh.template
--- a/bazel/avd/emulator_launcher.sh.template
+++ b/bazel/avd/emulator_launcher.sh.template
@@ -9,6 +9,10 @@
 # The path to the source.properties inside the system image.
 source_properties_path="%source_properties_path%"
 
+# Boot time might vary depending on API level. The value below was tested
+# with API level 30 (rvc).
+emulator_boot_timeout=70
+
 # Set environment variables.
 export HOME=$(pwd)
 export ANDROID_SDK_HOME=$HOME
@@ -20,18 +24,16 @@ export ANDROID_AVD_HOME=$ANDROID_EMULATOR_HOME/avd
 emulator=prebuilts/android-emulator/linux-x86_64/emulator
 adb=prebuilts/studio/sdk/linux/platform-tools/adb
 
-# Clear emulator files.
-rm -rf .android
-mkdir .android
-
 # Kill the emulator if requested. This is needed to kill the emulator for
 # local development.
 if [ "$1" = "kill" ]; then
   echo "Killing emulator-$2"
-  $adb -s emulator-$2 emu kill
+  $adb -s emulator-$2 emu kill 2> /dev/null
 
   # Wait for the emulator to disconnect.
   while true; do
+    # Update adb to make sure it knows the emulator is killed.
+    $adb reconnect 2>&1
     output=$($adb -s emulator-$2 get-state 2> /dev/null)
     if [ -z "$output" ]; then
       break
@@ -41,6 +43,10 @@ if [ "$1" = "kill" ]; then
   done
   exit $?
 fi
+
+# Clear emulator files.
+rm -rf .android 2> /dev/null
+mkdir .android 2> /dev/null
 
 # Read system image properties.
 api_level="$(cat $source_properties_path | sed -rn 's/AndroidVersion.ApiLevel=(.*)/\1/p')"
@@ -90,31 +96,38 @@ EOF
 
 # Launch the emulator.
 echo "Launching emulator-$1"
-$emulator @emu -no-window -port $1 &
-emu_pid=$!
+boot_complete=false
+# Try to launch the emulator. Keep relaunching if it takes too long.
+for i in 1 2 3
+do
+  start_time=$SECONDS
 
-# Wait for the emulator to connect.
-echo "Waiting for emulator to connect to ADB"
-while true; do
-  output=$($adb -s emulator-$1 get-state 2> /dev/null)
-  if [ "$output" = "device" ]; then
+  $emulator @emu -no-window -port $1 -delay-adb -no-snapshot -read-only 2>&1 &
+  emu_pid=$!
+
+  # Wait for the emulator to boot.
+  echo "Waiting for emulator to boot"
+  while true; do
+    output=$($adb -s emulator-$1 shell getprop sys.boot_completed 2>&1)
+    if [ "$output" = "1" ]; then
+      boot_complete=true
+      break
+    fi
+    elapsed_time=$(( SECONDS - start_time ))
+    if [ "$elapsed_time" -gt "$emulator_boot_timeout" ]; then
+      break
+    fi
+    sleep 1
+  done
+  if [ "$boot_complete" = true ]; then
     break
   fi
-  if ! kill -0 $emu_pid 2> /dev/null; then
-    exit 1
-  fi
-  sleep 1
+  echo "Emulator failed to come online in $emulator_boot_timeout seconds. Retrying $i ..."
+  kill -9 $emu_pid 2> /dev/null
 done
-
-# Wait for the emulator to boot.
-echo "Waiting for emulator to boot"
-while true; do
-  output=$($adb -s emulator-$1 shell getprop sys.boot_completed)
-  if [ "$output" = "1" ]; then
-    break
-  fi
-  if ! kill -0 $emu_pid 2> /dev/null; then
-    exit 1
-  fi
-  sleep 1
-done
+if [ "$boot_complete" = true ]; then
+  echo "Emulator boot complete"
+else
+  echo "Emulator boot failed"
+  exit 1
+fi
